version: '3'

services:
  webserver:
    build: .
    init: true
    restart: always
    container_name: cv-webserver
    command: bun run ./src/app.ts
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - ${PORT}:80
